import type {Locale} from './types';
const uk = {
 search:'Пошук матеріалу',placeholder:'Назва або код…',family:'Матеріал',all:'Усі',natural:'Натуральний камінь',sm:'Santa Margherita',type:'Тип каменю',collection:'Виробник / колекція',finish:'Обробка поверхні',thickness:'Товщина',availability:'Наявність',inStock:'Є за даними імпорту',outOfStock:'Немає за даними імпорту',sort:'Сортування',recommended:'Спочатку наявні',name:'За назвою',priceAsc:'Ціна: за зростанням',priceDesc:'Ціна: за спаданням',reset:'Скинути фільтри',samples:'Показати також зразкові слеби',count:'Знайдено позицій',empty:'За цими умовами матеріалів не знайдено. Спробуйте змінити фільтри.',noPhoto:'Фото очікується',details:'Картка матеріалу',perM2:'/ м²',perSlab:'/ цілий слеб',perFragment:'/ фрагмент',sample:'Зразковий слеб',fragment:'Фрагмент',format:'Формат',mm:'мм',back:'До каталогу',specs:'Характеристики',manufacturer:'Виробник',code:'Код виробника',surfacePending:'Обробку уточнюємо',pricePending:'Ціну уточнюємо',request:'Уточнити в ALTACO',source:'Джерело фото й опису типу',photoNote:'Фактура з прайсу ALTACO. Фото показує характер матеріалу; конкретний слеб погоджується окремо.',snapshot:'Імпорт',freshness:'Автоматичного оновлення поки немає. Дату актуальності джерела не підтверджено; наявність і ціну перед замовленням уточнює менеджер.',vat:'Ціни в EUR, з ПДВ.',noJs:'Пошук і фільтри працюють з JavaScript. Усі товарні позиції та їхні картки доступні нижче.',related:'Інші варіанти цього матеріалу',catalog:'Каталог матеріалів',pendingNote:'Значення в джерелі потребує перевірки; підтверджену ціну надасть менеджер.',finishNote:'У складській таблиці та прайсі різні позначення поверхні. Уточніть обробку перед вибором.',sampleNote:'Позиція належить до розділу зразкових слебів. Можливість продажу уточнюється.',pricing:'Ціна',productInfo:'Матеріал, обробка та формат зі складського переліку ALTACO.',contactSubject:'Запит щодо матеріалу',more:'Показати ще',summary:'Фото, характеристики та роздрібні ціни складських позицій.'
};
const en:Record<keyof typeof uk,string> = {
 search:'Search materials',placeholder:'Name or code…',family:'Material',all:'All',natural:'Natural stone',sm:'Santa Margherita',type:'Stone type',collection:'Manufacturer / collection',finish:'Surface finish',thickness:'Thickness',availability:'Availability',inStock:'Available at import',outOfStock:'Unavailable at import',sort:'Sort by',recommended:'Available first',name:'Name',priceAsc:'Price: low to high',priceDesc:'Price: high to low',reset:'Reset filters',samples:'Include sample slabs',count:'Matching variants',empty:'No materials match these filters. Try changing your selection.',noPhoto:'Photo pending',details:'Material details',perM2:'/ m²',perSlab:'/ whole slab',perFragment:'/ fragment',sample:'Sample slab',fragment:'Fragment',format:'Format',mm:'mm',back:'Back to catalogue',specs:'Specifications',manufacturer:'Manufacturer',code:'Manufacturer code',surfacePending:'Finish pending confirmation',pricePending:'Price pending',request:'Ask ALTACO',source:'Photo and material type source',photoNote:'Texture from the ALTACO price list. It illustrates the material; the actual slab is agreed separately.',snapshot:'Imported',freshness:'No automatic updates yet. The source effective date is unconfirmed; a manager confirms availability and price before ordering.',vat:'Prices in EUR, including VAT.',noJs:'Search and filters require JavaScript. All products and their detail pages remain available below.',related:'Other variants of this material',catalog:'Material catalogue',pendingNote:'The source value needs verification. A manager will provide the confirmed price.',finishNote:'The stock table and price list use different finish labels. Confirm the finish before selection.',sampleNote:'This item belongs to the sample slab section. Sale availability requires confirmation.',pricing:'Price',productInfo:'Material, finish and format from the ALTACO stock list.',contactSubject:'Material enquiry',more:'Show more',summary:'Photos, specifications and retail prices of stock variants.'
};
export const labels = (locale:Locale) => locale==='uk'?uk:en;
export function materialLabel(value:string,locale:Locale) {
 const types:Record<string,[string,string]> = {granite:['Граніт','Granite'],marble:['Мармур','Marble'],quartzite:['Кварцит','Quartzite'],travertine:['Травертин','Travertine'],'quartz-agglomerate':['Кварцовий агломерат','Quartz agglomerate'],'natural-stone':['Натуральний камінь','Natural stone']};
 return types[value]?.[locale==='uk'?0:1]??value;
}
